export enum ActionMenuScreenType {
  Base,
  CombatActionSelected,
  AssignAttributePoints,
  InventoryItems,
  ViewingEquipedItems,
  ItemSelected,
  CraftingActionSelection,
  ItemsOnGround,
  OperatingVendingMachine,
  PurchasingItems,
  CraftingItemSelection,
  RepairItemSelection,
  ShardItemSelection,
  ConfimConvertToShards,
  ViewingAbilityTree,
  ConsideringAbilityTreeColumn,
  ConsideringAbilityTreeAbility,
  SelectingBookType,
  SelectItemToTradeForBook,
  ConfirmTradeForBook,
}

export const MENU_STATE_TYPE_STRINGS: Record<ActionMenuScreenType, string> = {
  [ActionMenuScreenType.Base]: "Action Menu",
  [ActionMenuScreenType.CombatActionSelected]: "Combat action selected",
  [ActionMenuScreenType.AssignAttributePoints]: "Assigning attribute points",
  [ActionMenuScreenType.InventoryItems]: "Inventory",
  [ActionMenuScreenType.ViewingEquipedItems]: "Viewing equipped items",
  [ActionMenuScreenType.ItemSelected]: "Considering item",
  [ActionMenuScreenType.CraftingActionSelection]: "Selecting crafting action",
  [ActionMenuScreenType.ItemsOnGround]: "Viewing items on ground",
  [ActionMenuScreenType.OperatingVendingMachine]: "Operating vending machine",
  [ActionMenuScreenType.PurchasingItems]: "Purchasing items",
  [ActionMenuScreenType.CraftingItemSelection]: "Selecting item to craft",
  [ActionMenuScreenType.RepairItemSelection]: "Selecting item to repair",
  [ActionMenuScreenType.ShardItemSelection]: "Converting items to shards",
  [ActionMenuScreenType.ConfimConvertToShards]: "Confirm item destruction",
  [ActionMenuScreenType.ViewingAbilityTree]: "Viewing ability tree",
  [ActionMenuScreenType.ConsideringAbilityTreeColumn]: "Considering abilities",
  [ActionMenuScreenType.ConsideringAbilityTreeAbility]: "Considering ability",
  [ActionMenuScreenType.SelectingBookType]: "Selecting skill book",
  [ActionMenuScreenType.SelectItemToTradeForBook]: "Selecting item to trade",
  [ActionMenuScreenType.ConfirmTradeForBook]: "Confirming trade",
};
