// GENERATED FILE — do not edit by hand.
// Source: packages/balance-tools/game-data.xlsx
// Regenerate with: yarn workspace @speed-dungeon/balance-tools sync
import {
  CombatAttribute,
  CombatantClass,
  MonsterType,
} from "./attribute-table-dependencies.js";
import type { CombatantAttributeRecord } from "./attribute-table-dependencies.js";

export const BASE_STARTING_ATTRIBUTES: Record<CombatantClass, CombatantAttributeRecord> = {
  [CombatantClass.Warrior]: {
    [CombatAttribute.Speed]: 1,
    [CombatAttribute.Accuracy]: 80,
    [CombatAttribute.Hp]: 20,
    [CombatAttribute.Mp]: 2,
  },
  [CombatantClass.Rogue]: {
    [CombatAttribute.Speed]: 1,
    [CombatAttribute.Accuracy]: 90,
    [CombatAttribute.Hp]: 18,
    [CombatAttribute.Mp]: 3,
  },
  [CombatantClass.Mage]: {
    [CombatAttribute.Speed]: 1,
    [CombatAttribute.Accuracy]: 78,
    [CombatAttribute.Hp]: 15,
    [CombatAttribute.Mp]: 4,
  },
};

export const COMBATANT_CLASS_ATTRIBUTES_BY_LEVEL: Record<CombatantClass, CombatantAttributeRecord> = {
  [CombatantClass.Warrior]: {
    [CombatAttribute.Strength]: 2.5,
    [CombatAttribute.Dexterity]: 1.5,
    [CombatAttribute.Spirit]: 0.5,
    [CombatAttribute.Vitality]: 1.75,
    [CombatAttribute.Agility]: 0.75,
    [CombatAttribute.Hp]: 2,
    [CombatAttribute.Mp]: 1,
  },
  [CombatantClass.Rogue]: {
    [CombatAttribute.Strength]: 1.25,
    [CombatAttribute.Dexterity]: 2.5,
    [CombatAttribute.Spirit]: 0.75,
    [CombatAttribute.Vitality]: 1,
    [CombatAttribute.Agility]: 1.5,
    [CombatAttribute.Hp]: 1.5,
    [CombatAttribute.Mp]: 1.5,
  },
  [CombatantClass.Mage]: {
    [CombatAttribute.Strength]: 1,
    [CombatAttribute.Dexterity]: 1.75,
    [CombatAttribute.Spirit]: 2.5,
    [CombatAttribute.Vitality]: 1,
    [CombatAttribute.Agility]: 0.75,
    [CombatAttribute.Hp]: 1,
    [CombatAttribute.Mp]: 2,
  },
};

export const MONSTER_STARTING_ATTRIBUTES: Record<MonsterType, CombatantAttributeRecord> = {
  [MonsterType.Wolf]: {
    [CombatAttribute.Strength]: 100,
    [CombatAttribute.Vitality]: 1,
    [CombatAttribute.Speed]: 2,
    [CombatAttribute.ArmorClass]: 0,
    [CombatAttribute.Accuracy]: 70,
    [CombatAttribute.Hp]: 4,
  },
  [MonsterType.FireMage]: {
    [CombatAttribute.Spirit]: 4,
    [CombatAttribute.Vitality]: 1.5,
    [CombatAttribute.Speed]: 1,
    [CombatAttribute.Accuracy]: 60,
    [CombatAttribute.Hp]: 3,
  },
  [MonsterType.Cultist]: {
    [CombatAttribute.Strength]: 20,
    [CombatAttribute.Dexterity]: 20,
    [CombatAttribute.Spirit]: 6,
    [CombatAttribute.Speed]: 5,
    [CombatAttribute.Accuracy]: 0,
    [CombatAttribute.Evasion]: 0,
    [CombatAttribute.Hp]: 40,
  },
  [MonsterType.MantaRay]: {
    [CombatAttribute.Spirit]: 8,
    [CombatAttribute.Vitality]: 1,
    [CombatAttribute.Speed]: 1,
    [CombatAttribute.Accuracy]: 100,
    [CombatAttribute.Hp]: 1,
  },
  [MonsterType.Net]: {
    [CombatAttribute.Speed]: 10,
    [CombatAttribute.Hp]: 3,
  },
  [MonsterType.Spider]: {
    [CombatAttribute.Strength]: 2,
    [CombatAttribute.Dexterity]: 7,
    [CombatAttribute.Vitality]: 1.5,
    [CombatAttribute.Agility]: 2,
    [CombatAttribute.Speed]: 2,
    [CombatAttribute.Accuracy]: 80,
    [CombatAttribute.Hp]: 35,
    [CombatAttribute.Mp]: 2,
  },
  [MonsterType.Slime]: {
    [CombatAttribute.Strength]: 2,
    [CombatAttribute.Dexterity]: 4,
    [CombatAttribute.Spirit]: 0,
    [CombatAttribute.Vitality]: 1.5,
    [CombatAttribute.Agility]: 0,
    [CombatAttribute.Speed]: 1,
    [CombatAttribute.Accuracy]: 80,
    [CombatAttribute.Hp]: 5,
    [CombatAttribute.Mp]: 0,
  },
  [MonsterType.Zombie]: {
    [CombatAttribute.Strength]: 50,
    [CombatAttribute.Vitality]: 0,
    [CombatAttribute.Speed]: 1,
    [CombatAttribute.ArmorClass]: 0,
    [CombatAttribute.Accuracy]: 55,
    [CombatAttribute.Hp]: 7,
  },
  [MonsterType.SkeletonWarrior]: {
    [CombatAttribute.Strength]: 2,
    [CombatAttribute.Vitality]: 2,
    [CombatAttribute.Speed]: 1,
    [CombatAttribute.ArmorClass]: 0,
    [CombatAttribute.Accuracy]: 70,
    [CombatAttribute.Hp]: 1,
  },
  [MonsterType.SkeletonCaptain]: {
    [CombatAttribute.Strength]: 4,
    [CombatAttribute.Dexterity]: 1,
    [CombatAttribute.Vitality]: 2,
    [CombatAttribute.Speed]: 1,
    [CombatAttribute.ArmorClass]: 0,
    [CombatAttribute.Accuracy]: 70,
    [CombatAttribute.Hp]: 2,
  },
  [MonsterType.VampireBat]: {
    [CombatAttribute.Strength]: 1,
    [CombatAttribute.Dexterity]: 2,
    [CombatAttribute.Vitality]: 0,
    [CombatAttribute.Speed]: 2,
    [CombatAttribute.ArmorClass]: 0,
    [CombatAttribute.Accuracy]: 65,
    [CombatAttribute.Hp]: 1.5,
  },
  [MonsterType.TyrantRex]: {
    [CombatAttribute.Strength]: 5,
    [CombatAttribute.Dexterity]: 5,
    [CombatAttribute.Spirit]: 0,
    [CombatAttribute.Vitality]: 3,
    [CombatAttribute.Agility]: 2,
    [CombatAttribute.ArmorClass]: 1.5,
    [CombatAttribute.Accuracy]: 70,
    [CombatAttribute.Evasion]: 3,
    [CombatAttribute.Hp]: 70,
    [CombatAttribute.Mp]: 0,
  },
};

export const MONSTER_ATTRIBUTES_BY_LEVEL: Record<MonsterType, CombatantAttributeRecord> = {
  [MonsterType.Wolf]: {
    [CombatAttribute.Strength]: 7,
    [CombatAttribute.Dexterity]: 8,
    [CombatAttribute.Vitality]: 1.5,
    [CombatAttribute.Agility]: 2,
    [CombatAttribute.ArmorClass]: 4.5,
    [CombatAttribute.Evasion]: 10,
    [CombatAttribute.Hp]: 4.5,
    [CombatAttribute.Mp]: 0,
  },
  [MonsterType.FireMage]: {
    [CombatAttribute.Spirit]: 10,
    [CombatAttribute.Vitality]: 1.5,
    [CombatAttribute.Agility]: 1.5,
    [CombatAttribute.ArmorClass]: 2.5,
    [CombatAttribute.Evasion]: 1,
    [CombatAttribute.Hp]: 4.5,
  },
  [MonsterType.Cultist]: {
    [CombatAttribute.Spirit]: 14,
    [CombatAttribute.Agility]: 1.5,
    [CombatAttribute.Evasion]: 0,
    [CombatAttribute.Hp]: 0,
  },
  [MonsterType.MantaRay]: {
    [CombatAttribute.Spirit]: 6,
    [CombatAttribute.Vitality]: 1,
    [CombatAttribute.Agility]: 1.5,
    [CombatAttribute.Hp]: 22,
  },
  [MonsterType.Net]: {
    [CombatAttribute.Speed]: 10,
  },
  [MonsterType.Spider]: {
    [CombatAttribute.Strength]: 8,
    [CombatAttribute.Dexterity]: 6,
    [CombatAttribute.Vitality]: 1.5,
    [CombatAttribute.Agility]: 2,
    [CombatAttribute.ArmorClass]: 7.5,
    [CombatAttribute.Evasion]: 12,
    [CombatAttribute.Hp]: 4.5,
    [CombatAttribute.Mp]: 0,
  },
  [MonsterType.Slime]: {
    [CombatAttribute.Strength]: 3,
    [CombatAttribute.Dexterity]: 3,
    [CombatAttribute.Spirit]: 2,
    [CombatAttribute.Vitality]: 0.5,
    [CombatAttribute.Agility]: 1,
    [CombatAttribute.ArmorClass]: 2,
    [CombatAttribute.Evasion]: 6,
    [CombatAttribute.Hp]: 3.5,
    [CombatAttribute.Mp]: 0,
  },
  [MonsterType.Zombie]: {
    [CombatAttribute.Strength]: 5,
    [CombatAttribute.Dexterity]: 3,
    [CombatAttribute.Vitality]: 2.5,
    [CombatAttribute.Agility]: 2,
    [CombatAttribute.ArmorClass]: 4.5,
    [CombatAttribute.Evasion]: 2,
    [CombatAttribute.Hp]: 4.5,
    [CombatAttribute.Mp]: 0,
  },
  [MonsterType.SkeletonWarrior]: {
    [CombatAttribute.Strength]: 4,
    [CombatAttribute.Dexterity]: 4,
    [CombatAttribute.Vitality]: 2,
    [CombatAttribute.Agility]: 2,
    [CombatAttribute.ArmorClass]: 7.5,
    [CombatAttribute.Evasion]: 2,
    [CombatAttribute.Hp]: 3.5,
    [CombatAttribute.Mp]: 0,
  },
  [MonsterType.SkeletonCaptain]: {
    [CombatAttribute.Strength]: 4,
    [CombatAttribute.Dexterity]: 5,
    [CombatAttribute.Spirit]: 2,
    [CombatAttribute.Vitality]: 2,
    [CombatAttribute.Agility]: 2,
    [CombatAttribute.ArmorClass]: 7.5,
    [CombatAttribute.Evasion]: 2,
    [CombatAttribute.Hp]: 3.5,
    [CombatAttribute.Mp]: 0,
  },
  [MonsterType.VampireBat]: {
    [CombatAttribute.Strength]: 2,
    [CombatAttribute.Dexterity]: 5,
    [CombatAttribute.Spirit]: 2,
    [CombatAttribute.Vitality]: 1,
    [CombatAttribute.Agility]: 3,
    [CombatAttribute.ArmorClass]: 1.5,
    [CombatAttribute.Evasion]: 3,
    [CombatAttribute.Hp]: 1.5,
    [CombatAttribute.Mp]: 0,
  },
  [MonsterType.TyrantRex]: {
    [CombatAttribute.Strength]: 5,
    [CombatAttribute.Dexterity]: 5,
    [CombatAttribute.Spirit]: 0,
    [CombatAttribute.Vitality]: 3,
    [CombatAttribute.Agility]: 2,
    [CombatAttribute.ArmorClass]: 1.5,
    [CombatAttribute.Evasion]: 3,
    [CombatAttribute.Hp]: 3.5,
    [CombatAttribute.Mp]: 0,
  },
};
