export enum CombatActionName {
  Attack,
  AttackMeleeMainhand,
  AttackMeleeOffhand,
  AttackRangedMainhand,
  AttackRangedMainhandProjectile,
  Counterattack,
  CounterattackMeleeMainhand,
  CounterattackMeleeOffhand,
  CounterattackRangedMainhand,
  ChainingSplitArrowParent,
  ChainingSplitArrowProjectile,
  ExplodingArrowParent,
  ExplodingArrowProjectile,
  Explosion,
  // Fire,
  IceBoltParent,
  IceBoltProjectile,
  IceBurst,
  // Healing,
  // Destruction,
  UseGreenAutoinjector,
  UseBlueAutoinjector,
}

export const ACTION_NAMES_TO_HIDE_IN_MENU = [
  CombatActionName.UseGreenAutoinjector,
  CombatActionName.UseBlueAutoinjector,
];

export const COMBAT_ACTION_NAME_STRINGS: Record<CombatActionName, string> = {
  [CombatActionName.Attack]: "Attack",
  [CombatActionName.AttackMeleeMainhand]: "Attack Melee Mainhand",
  [CombatActionName.AttackMeleeOffhand]: "Attack Melee Offhand",
  [CombatActionName.AttackRangedMainhand]: "Attack Ranged Mainhand",
  [CombatActionName.AttackRangedMainhandProjectile]: "Attack Ranged Mainhand Projectile",
  [CombatActionName.Counterattack]: "Counterattack",
  [CombatActionName.CounterattackMeleeMainhand]: "Counterattack Melee MainHand",
  [CombatActionName.CounterattackMeleeOffhand]: "Counterattack Melee OffHand",
  [CombatActionName.CounterattackRangedMainhand]: "Counterattack Ranged Main Hand",
  [CombatActionName.ChainingSplitArrowParent]: "Chaining Split Arrow",
  [CombatActionName.ChainingSplitArrowProjectile]: "Chaining Split Arrow Projectile",
  [CombatActionName.ExplodingArrowParent]: "Exploding Arrow",
  [CombatActionName.ExplodingArrowProjectile]: "Exploding Arrow Projectile",
  [CombatActionName.Explosion]: "Explosion",
  [CombatActionName.IceBoltParent]: "Ice Bolt",
  [CombatActionName.IceBoltProjectile]: "Ice Bolt Projectile",
  [CombatActionName.IceBurst]: "Ice Burst",
  [CombatActionName.UseGreenAutoinjector]: "Green Autoinjector",
  [CombatActionName.UseBlueAutoinjector]: "Blue Autoinjector",
};
