export enum CombatActionName {
  Attack,
  AttackMeleeMainhand,
  AttackMeleeOffhand,
  AttackRangedMainhand,
  AttackRangedMainhandProjectile,
  CounterAttackRangedMainhandProjectile,
  Counterattack,
  CounterattackMeleeMainhand,
  CounterattackRangedMainhand,
  ChainingSplitArrowParent,
  ChainingSplitArrowProjectile,
  ExplodingArrowParent,
  ExplodingArrowProjectile,
  Explosion,
  IceBoltParent,
  IceBoltProjectile,
  IceBurst,
  Fire,
  BurningTick,
  Healing,
  // Destruction,
  UseGreenAutoinjector,
  UseBlueAutoinjector,
  PassTurn,
  ConditionPassTurn,
  Blind,
  PayActionPoint, // useful for charging action points for swapping weapons and maybe other things
}

export const ACTION_NAMES_TO_HIDE_IN_MENU = [
  CombatActionName.UseGreenAutoinjector,
  CombatActionName.UseBlueAutoinjector,
  CombatActionName.AttackMeleeMainhand,
  CombatActionName.AttackMeleeOffhand,
  CombatActionName.AttackRangedMainhand,
];

export const COMBAT_ACTION_NAME_STRINGS: Record<CombatActionName, string> = {
  [CombatActionName.Attack]: "Attack",
  [CombatActionName.AttackMeleeMainhand]: "Attack Melee Mainhand",
  [CombatActionName.AttackMeleeOffhand]: "Attack Melee Offhand",
  [CombatActionName.AttackRangedMainhand]: "Attack Ranged Mainhand",
  [CombatActionName.AttackRangedMainhandProjectile]: "Attack Ranged Mainhand Projectile",
  [CombatActionName.CounterAttackRangedMainhandProjectile]:
    "Counter Attack Ranged Mainhand Projectile",
  [CombatActionName.Counterattack]: "Counterattack",
  [CombatActionName.CounterattackMeleeMainhand]: "Counterattack Melee MainHand",
  [CombatActionName.CounterattackRangedMainhand]: "Counterattack Ranged Main Hand",
  [CombatActionName.ChainingSplitArrowParent]: "Chaining Split Arrow",
  [CombatActionName.ChainingSplitArrowProjectile]: "Chaining Split Arrow Projectile",
  [CombatActionName.ExplodingArrowParent]: "Exploding Arrow",
  [CombatActionName.ExplodingArrowProjectile]: "Exploding Arrow Projectile",
  [CombatActionName.Explosion]: "Explosion",
  [CombatActionName.IceBoltParent]: "Ice Bolt",
  [CombatActionName.IceBoltProjectile]: "Ice Bolt Projectile",
  [CombatActionName.IceBurst]: "Ice Burst",
  [CombatActionName.Fire]: "Fire",
  [CombatActionName.Healing]: "Healing",
  [CombatActionName.UseGreenAutoinjector]: "Green Autoinjector",
  [CombatActionName.UseBlueAutoinjector]: "Blue Autoinjector",
  [CombatActionName.BurningTick]: "Burning Tick",
  [CombatActionName.PassTurn]: "Pass Turn",
  [CombatActionName.ConditionPassTurn]: "Condition Pass Turn",
  [CombatActionName.Blind]: "Blind",
  [CombatActionName.PayActionPoint]: "Pay Action Point",
};
