export const RANDOM_GAME_NAMES_FIRST = [
  "strange",
  "silent",
  "dark",
  "eerie",
  "spooky",
  "creaky",
  "rotten",
  "forgotten",
  "unsettling",
  "uncanny",
];

export const RANDOM_GAME_NAMES_LAST = [
  "ravine",
  "cave",
  "hill",
  "valley",
  "tunnel",
  "sewer",
  "underground",
  "descent",
  "catacomb",
  "rift",
  "cellar",
  "mine",
  "nest",
  "tomb",
  "crypt",
  "canyon",
  "forest",
];

export const RANDOM_PARTY_NAMES = [
  "The Bad Batch",
  "Team 17",
  "Royalty",
  "Don't Stop Believin'",
  "Streetlight Manifesto",
  "The Expendables",
  "The Crew of Moya",
  "The Attenders",
  "Descender's Anonymous",
  "Hello Kitty Bike Club",
];
