import { CombatAttribute } from "../../attributes/index.js";
import { CombatantClass } from "./classes.js";

export const COMBATANT_CLASS_ATTRIBUTES_BY_LEVEL: Record<
  CombatantClass,
  Partial<Record<CombatAttribute, number>>
> = {
  [CombatantClass.Warrior]: {
    [CombatAttribute.ArmorPenetration]: 0,
    [CombatAttribute.Accuracy]: 0,
    [CombatAttribute.ArmorClass]: 0,
    [CombatAttribute.Evasion]: 0,
    [CombatAttribute.Hp]: 2.0,
    [CombatAttribute.Speed]: 0,
    [CombatAttribute.Mp]: 1.0,
    [CombatAttribute.Strength]: 2.5,
    [CombatAttribute.Dexterity]: 1.5,
    [CombatAttribute.Intelligence]: 0,
    [CombatAttribute.Focus]: 0,
    [CombatAttribute.Vitality]: 2.0,
    [CombatAttribute.Resilience]: 1.0,
    [CombatAttribute.Agility]: 1.0,
  },
  [CombatantClass.Mage]: {
    [CombatAttribute.ArmorPenetration]: 0,
    [CombatAttribute.Accuracy]: 0,
    [CombatAttribute.ArmorClass]: 0,
    [CombatAttribute.Evasion]: 0,
    [CombatAttribute.Hp]: 1.0,
    [CombatAttribute.Speed]: 0,
    [CombatAttribute.Mp]: 2.0,
    [CombatAttribute.Strength]: 0.5,
    [CombatAttribute.Dexterity]: 0.5,
    [CombatAttribute.Intelligence]: 2.5,
    [CombatAttribute.Focus]: 2.0,
    [CombatAttribute.Vitality]: 1.0,
    [CombatAttribute.Resilience]: 1.5,
    [CombatAttribute.Agility]: 0.5,
  },
  [CombatantClass.Rogue]: {
    [CombatAttribute.ArmorPenetration]: 0,
    [CombatAttribute.Accuracy]: 0,
    [CombatAttribute.ArmorClass]: 0,
    [CombatAttribute.Evasion]: 0,
    [CombatAttribute.Hp]: 1.5,
    [CombatAttribute.Speed]: 0,
    [CombatAttribute.Mp]: 1.5,
    [CombatAttribute.Strength]: 1.5,
    [CombatAttribute.Dexterity]: 2.0,
    [CombatAttribute.Intelligence]: 1.0,
    [CombatAttribute.Focus]: 0,
    [CombatAttribute.Vitality]: 1.5,
    [CombatAttribute.Resilience]: 1.5,
    [CombatAttribute.Agility]: 1.5,
  },
};
