export enum TwoHandedMeleeWeapon {
  RottingBranch,
  BoStaff,
  Spear,
  Bardiche,
  SplittingMaul,
  Maul,
  BattleAxe,
  Glaive,
  ElementalStaff,
  Trident,
  GreatAxe,
  GravityHammer,
  // FOR MAGES
  ElmStaff,
  MahoganyStaff,
  EbonyStaff,
}

export const TWO_HANDED_MELEE_WEAPON_TYPE_STRINGS: Record<TwoHandedMeleeWeapon, string> = {
  [TwoHandedMeleeWeapon.RottingBranch]: "Rotting Branch",
  [TwoHandedMeleeWeapon.BoStaff]: "Bo Staff",
  [TwoHandedMeleeWeapon.Spear]: "Spear",
  [TwoHandedMeleeWeapon.Bardiche]: "Bardiche",
  [TwoHandedMeleeWeapon.SplittingMaul]: "Splitting Maul",
  [TwoHandedMeleeWeapon.Maul]: "Maul",
  [TwoHandedMeleeWeapon.BattleAxe]: "Battle Axe",
  [TwoHandedMeleeWeapon.Glaive]: "Glaive",
  [TwoHandedMeleeWeapon.ElementalStaff]: "Elemental Staff",
  [TwoHandedMeleeWeapon.Trident]: "Trident",
  [TwoHandedMeleeWeapon.GreatAxe]: "Great Axe",
  [TwoHandedMeleeWeapon.GravityHammer]: "Gravity Hammer",
  [TwoHandedMeleeWeapon.ElmStaff]: "Elm Staff",
  [TwoHandedMeleeWeapon.MahoganyStaff]: "Mahogany Staff",
  [TwoHandedMeleeWeapon.EbonyStaff]: "Ebony Staff",
};
