version: "3.8"
services:
  speed-dungeon-postgres:
    image: postgres:16
    container_name: speed-dungeon-postgres
    volumes:
      - speed-dungeon-postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
    ports:
      - 5433:5432
  speed-dungeon-valkey:
    image: valkey/valkey
    container_name: speed-dungeon-valkey
    ports:
      - 6380:6379
    volumes:
      - speed-dungeon-valkey:/data
volumes:
  speed-dungeon-postgres_data:
  speed-dungeon-valkey:


