export const PLAYER_FIRST_NAMES = [
  "obi-wan",
  "qui-gon",
  "slayers",
  "leon",
  "claire",
  "chris",
  "rebecca",
  "albert",
  "vivi",
  "zidane",
  "garnet",
  "adelbert",
  "rick",
  "maggie",
  "daryl",
  "carol",
];
export const PLAYER_LAST_NAMES = [
  "kenobi",
  "jin",
  "boxer",
  "kennedy",
  "redfield",
  "chambers",
  "wesker",
  "ortainer",
  "tribal",
  "til alexandros XVII",
  "steiner",
  "grimes",
  "dixon",
  "peletier",
];

export const RANDOM_GAME_NAMES_FIRST = [
  "strange",
  "silent",
  "dark",
  "eerie",
  "spooky",
  "creaky",
  "rotten",
  "forgotten",
  "unsettling",
  "uncanny",
];

export const RANDOM_GAME_NAMES_LAST = [
  "ravine",
  "cave",
  "hill",
  "valley",
  "tunnel",
  "sewer",
  "underground",
  "descent",
  "catacomb",
  "rift",
  "cellar",
  "mine",
  "nest",
  "tomb",
  "crypt",
  "canyon",
  "forest",
];

export const RANDOM_PARTY_NAMES = [
  "The Bad Batch",
  "Team 17",
  "Royalty",
  "Don't Stop Believin'",
  "Streetlight Manifesto",
  "The Expendables",
  "The Crew of Moya",
  "The Attenders",
  "Descender's Anonymous",
];

// export const RANDOM_CHARACTER_NAMES_FIRST: [&str; 10] = [
//     "King Reaver",
//     "One Treetrunk",
//     "Six Link",
//     "Jennifer",
//     "Bill",
//     "Omar",
//     "Honalulu",
//     "Kalawao",
//     "Maui",
//     "Alexander",
// ];

// export const RANDOM_CHARACTER_NAMES_LAST: [&str; 10] = [
//     "Kirito",
//     "Once",
//     "Voltaxic",
//     "Melphi",
//     "Murray",
//     "Little",
//     "Island",
//     "the Destroyer",
//     "the Great",
//     "Hammer",
// ];

export const RANDOM_CHARACTER_NAMES_FIRST = [
  "Kirito",
  "Asuna",
  "Klein",
  "Eugeo",
  "Heathcliff",
  "Diabel",
  "Sachi",
  "Keita",
  "Silica",
  "Lisbeth",
  "Yui",
  "Agil",
];
