import { CombatAttribute } from "../combatants/attributes/index.js";
import { CombatantAttributeRecord } from "../combatants/combatant-attribute-record.js";
import { MonsterType } from "./monster-types.js";

export const MONSTER_STARTING_ATTRIBUTES: Record<MonsterType, CombatantAttributeRecord> = {
  [MonsterType.Net]: {
    [CombatAttribute.Speed]: 10,
    [CombatAttribute.Hp]: 3,
  },
  [MonsterType.Wolf]: {
    [CombatAttribute.Vitality]: 1.0,
    [CombatAttribute.ArmorClass]: 0.0,
    [CombatAttribute.Hp]: 4,
    [CombatAttribute.Accuracy]: 70.0,
    [CombatAttribute.Strength]: 10.0,
    [CombatAttribute.Speed]: 2.0,
  },
  [MonsterType.Spider]: {
    [CombatAttribute.Dexterity]: 7.0,
    [CombatAttribute.Strength]: 2.0,
    [CombatAttribute.Vitality]: 1.5,
    [CombatAttribute.Hp]: 35.0,
    [CombatAttribute.Agility]: 2.0,
    [CombatAttribute.Accuracy]: 80.0,
    [CombatAttribute.Mp]: 2.0,
    [CombatAttribute.Speed]: 2.0,
  },
  [MonsterType.Slime]: {
    [CombatAttribute.Spirit]: 0.0,
    [CombatAttribute.Dexterity]: 4.0,
    [CombatAttribute.Strength]: 2.0,
    [CombatAttribute.Vitality]: 1.5,
    [CombatAttribute.Hp]: 5.0,
    [CombatAttribute.Agility]: 0,
    [CombatAttribute.Accuracy]: 80.0,
    [CombatAttribute.Mp]: 0.0,
    [CombatAttribute.Speed]: 1.0,
  },
  [MonsterType.Zombie]: {
    [CombatAttribute.Vitality]: 2.0,
    [CombatAttribute.ArmorClass]: 0.0,
    [CombatAttribute.Hp]: 3,
    [CombatAttribute.Accuracy]: 55.0,
    [CombatAttribute.Strength]: 5.0,
    [CombatAttribute.Speed]: 1,
  },
  [MonsterType.SkeletonWarrior]: {
    [CombatAttribute.Vitality]: 2.0,
    [CombatAttribute.ArmorClass]: 0.0,
    [CombatAttribute.Hp]: 1,
    [CombatAttribute.Accuracy]: 70.0,
    [CombatAttribute.Strength]: 2.0,
    [CombatAttribute.Speed]: 1,
  },
  [MonsterType.VampireBat]: {
    [CombatAttribute.Vitality]: 0.0,
    [CombatAttribute.ArmorClass]: 0.0,
    [CombatAttribute.Hp]: 1.5,
    [CombatAttribute.Accuracy]: 65.0,
    [CombatAttribute.Strength]: 1.0,
    [CombatAttribute.Dexterity]: 2.0,
    [CombatAttribute.Speed]: 2,
  },
  [MonsterType.SkeletonCaptain]: {
    [CombatAttribute.Vitality]: 2.0,
    [CombatAttribute.ArmorClass]: 0.0,
    [CombatAttribute.Hp]: 2,
    [CombatAttribute.Accuracy]: 70.0,
    [CombatAttribute.Strength]: 4.0,
    [CombatAttribute.Dexterity]: 1.0,
    [CombatAttribute.Speed]: 1,
  },
  [MonsterType.TyrantRex]: {
    [CombatAttribute.Dexterity]: 5.0,
    [CombatAttribute.Strength]: 5.0,
    [CombatAttribute.Spirit]: 0.0,
    [CombatAttribute.Vitality]: 3,
    [CombatAttribute.Accuracy]: 70.0,
    [CombatAttribute.Hp]: 40,
    [CombatAttribute.Mp]: 0.0,
    [CombatAttribute.Agility]: 2.0,
    [CombatAttribute.ArmorClass]: 1.5,
    [CombatAttribute.Evasion]: 3.0,
  },
  [MonsterType.FireMage]: {
    [CombatAttribute.Spirit]: 4.0,
    [CombatAttribute.Vitality]: 1.5,
    [CombatAttribute.Hp]: 3.0,
    [CombatAttribute.Accuracy]: 60.0,
    [CombatAttribute.Speed]: 1.0,
  },
  [MonsterType.Cultist]: {
    [CombatAttribute.Spirit]: 6.0,
    [CombatAttribute.Hp]: 40.0,
    [CombatAttribute.Strength]: 20,
    [CombatAttribute.Dexterity]: 20,
    [CombatAttribute.Accuracy]: 0.0,
    [CombatAttribute.Evasion]: 0.0,
    [CombatAttribute.Speed]: 5.0,
  },
  [MonsterType.MantaRay]: {
    [CombatAttribute.Spirit]: 8.0,
    [CombatAttribute.Vitality]: 1.0,
    [CombatAttribute.Hp]: 1.0,
    [CombatAttribute.Accuracy]: 100.0,
    [CombatAttribute.Speed]: 1.0,
  },
};
