// GENERATED FILE — do not edit by hand.
// Source: packages/balance-tools/game-data.xlsx
// Regenerate: yarn workspace @speed-dungeon/balance-tools sync
import {
  AffixType,
  Amulet,
  ArmorCategory,
  BodyArmor,
  CombatAttribute,
  EquipmentType,
  HeadGear,
  KineticDamageType,
  MagicalElement,
  NumberRange,
  OneHandedMeleeWeapon,
  ResourceChangeSource,
  ResourceChangeSourceCategory,
  Ring,
  Shield,
  ShieldSize,
  TwoHandedMeleeWeapon,
  TwoHandedRangedWeapon,
} from "./game-data-dependencies.js";
import type { EquipmentTemplateSpec } from "./game-data-dependencies.js";

export const EQUIPMENT_TEMPLATE_SPECS: EquipmentTemplateSpec[] = [
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.Stick,
    },
    levelRange: new NumberRange(0, 0),
    maxDurability: 8,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(1, 3),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.Club,
    },
    levelRange: new NumberRange(1, 3),
    maxDurability: 14,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(1, 4),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.Mace,
    },
    levelRange: new NumberRange(2, 5),
    maxDurability: 22,
    requirements: { [CombatAttribute.Strength]: 1 },
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(1, 8),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.Morningstar,
    },
    levelRange: new NumberRange(4, 8),
    maxDurability: 18,
    requirements: { [CombatAttribute.Strength]: 1 },
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(2, 12),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.WarHammer,
    },
    levelRange: new NumberRange(8, 10),
    maxDurability: 20,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(4, 16),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.ButterKnife,
    },
    levelRange: new NumberRange(0, 0),
    maxDurability: 7,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(1, 2),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Slashing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.ShortSword,
    },
    levelRange: new NumberRange(2, 4),
    maxDurability: 15,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(2, 6),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Slashing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.Blade,
    },
    levelRange: new NumberRange(3, 5),
    maxDurability: 17,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(4, 8),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Slashing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.BroadSword,
    },
    levelRange: new NumberRange(6, 8),
    maxDurability: 24,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(4, 12),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Slashing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.BastardSword,
    },
    levelRange: new NumberRange(8, 10),
    maxDurability: 25,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(6, 15),
    damageClassificationsCount: 2,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Slashing }),
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Piercing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.Dagger,
    },
    levelRange: new NumberRange(1, 3),
    maxDurability: 9,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(1, 4),
    damageClassificationsCount: 2,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Slashing }),
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Piercing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.Rapier,
    },
    levelRange: new NumberRange(3, 6),
    maxDurability: 13,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(1, 11),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Piercing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.ShortSpear,
    },
    levelRange: new NumberRange(6, 9),
    maxDurability: 25,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(4, 13),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Piercing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.RuneSword,
    },
    levelRange: new NumberRange(5, 10),
    maxDurability: 20,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(2, 12),
    damageClassificationsCount: 2,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Slashing, elementOption: MagicalElement.Fire }),
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Slashing, elementOption: MagicalElement.Ice }),
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Slashing, elementOption: MagicalElement.Lightning }),
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Slashing, elementOption: MagicalElement.Water }),
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Slashing, elementOption: MagicalElement.Earth }),
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Slashing, elementOption: MagicalElement.Wind }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.EtherBlade,
    },
    levelRange: new NumberRange(5, 8),
    maxDurability: 12,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(6, 10),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Magical, kineticDamageTypeOption: KineticDamageType.Slashing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.IceBlade,
    },
    levelRange: new NumberRange(2, 4),
    maxDurability: 9,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(2, 6),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Slashing, elementOption: MagicalElement.Ice }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.MapleWand,
    },
    levelRange: new NumberRange(2, 4),
    maxDurability: 10,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(1, 8),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Magical }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.WillowWand,
    },
    levelRange: new NumberRange(3, 6),
    maxDurability: 14,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(2, 10),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Magical }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.YewWand,
    },
    levelRange: new NumberRange(5, 7),
    maxDurability: 18,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(3, 13),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Magical }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.OneHandedMeleeWeapon,
      baseItemType: OneHandedMeleeWeapon.RoseWand,
    },
    levelRange: new NumberRange(8, 10),
    maxDurability: 24,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(6, 16),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Magical }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedMeleeWeapon,
      baseItemType: TwoHandedMeleeWeapon.RottingBranch,
    },
    levelRange: new NumberRange(0, 0),
    maxDurability: 6,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(1, 7),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedMeleeWeapon,
      baseItemType: TwoHandedMeleeWeapon.BoStaff,
    },
    levelRange: new NumberRange(1, 3),
    maxDurability: 8,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(2, 8),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedMeleeWeapon,
      baseItemType: TwoHandedMeleeWeapon.Spear,
    },
    levelRange: new NumberRange(2, 4),
    maxDurability: 11,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(3, 9),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Piercing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedMeleeWeapon,
      baseItemType: TwoHandedMeleeWeapon.Bardiche,
    },
    levelRange: new NumberRange(2, 4),
    maxDurability: 15,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(1, 11),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Slashing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedMeleeWeapon,
      baseItemType: TwoHandedMeleeWeapon.SplittingMaul,
    },
    levelRange: new NumberRange(4, 6),
    maxDurability: 16,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(6, 12),
    damageClassificationsCount: 2,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Slashing }),
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedMeleeWeapon,
      baseItemType: TwoHandedMeleeWeapon.Maul,
    },
    levelRange: new NumberRange(5, 7),
    maxDurability: 18,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(9, 14),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedMeleeWeapon,
      baseItemType: TwoHandedMeleeWeapon.BattleAxe,
    },
    levelRange: new NumberRange(5, 7),
    maxDurability: 21,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(6, 15),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Slashing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedMeleeWeapon,
      baseItemType: TwoHandedMeleeWeapon.Glaive,
    },
    levelRange: new NumberRange(6, 8),
    maxDurability: 19,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(8, 17),
    damageClassificationsCount: 2,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Slashing }),
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Piercing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedMeleeWeapon,
      baseItemType: TwoHandedMeleeWeapon.ElementalStaff,
    },
    levelRange: new NumberRange(7, 9),
    maxDurability: 18,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(10, 18),
    damageClassificationsCount: 2,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt, elementOption: MagicalElement.Fire }),
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt, elementOption: MagicalElement.Ice }),
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt, elementOption: MagicalElement.Lightning }),
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt, elementOption: MagicalElement.Water }),
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt, elementOption: MagicalElement.Earth }),
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt, elementOption: MagicalElement.Wind }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedMeleeWeapon,
      baseItemType: TwoHandedMeleeWeapon.Trident,
    },
    levelRange: new NumberRange(8, 10),
    maxDurability: 23,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(14, 26),
    damageClassificationsCount: 2,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Magical, elementOption: MagicalElement.Water }),
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Piercing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedMeleeWeapon,
      baseItemType: TwoHandedMeleeWeapon.GreatAxe,
    },
    levelRange: new NumberRange(9, 10),
    maxDurability: 28,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(15, 35),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Slashing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedMeleeWeapon,
      baseItemType: TwoHandedMeleeWeapon.GravityHammer,
    },
    levelRange: new NumberRange(9, 10),
    maxDurability: 40,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(20, 30),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedMeleeWeapon,
      baseItemType: TwoHandedMeleeWeapon.ElmStaff,
    },
    levelRange: new NumberRange(3, 6),
    maxDurability: 16,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.LifeSteal]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Spirit]: 5, [AffixType.Vitality]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(4, 12),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedMeleeWeapon,
      baseItemType: TwoHandedMeleeWeapon.MahoganyStaff,
    },
    levelRange: new NumberRange(5, 8),
    maxDurability: 19,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.LifeSteal]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Spirit]: 5, [AffixType.Vitality]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(8, 22),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedMeleeWeapon,
      baseItemType: TwoHandedMeleeWeapon.EbonyStaff,
    },
    levelRange: new NumberRange(8, 10),
    maxDurability: 24,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.LifeSteal]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Spirit]: 5, [AffixType.Vitality]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(10, 32),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Blunt }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedRangedWeapon,
      baseItemType: TwoHandedRangedWeapon.ShortBow,
    },
    levelRange: new NumberRange(1, 3),
    maxDurability: 15,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.Evasion]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(2, 7),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Piercing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedRangedWeapon,
      baseItemType: TwoHandedRangedWeapon.RecurveBow,
    },
    levelRange: new NumberRange(3, 5),
    maxDurability: 16,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.Evasion]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(5, 10),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Piercing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedRangedWeapon,
      baseItemType: TwoHandedRangedWeapon.CompositeBow,
    },
    levelRange: new NumberRange(5, 8),
    maxDurability: 26,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.Evasion]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(8, 16),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Piercing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedRangedWeapon,
      baseItemType: TwoHandedRangedWeapon.MilitaryBow,
    },
    levelRange: new NumberRange(8, 10),
    maxDurability: 25,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.Evasion]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(12, 26),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Physical, kineticDamageTypeOption: KineticDamageType.Piercing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.TwoHandedRangedWeapon,
      baseItemType: TwoHandedRangedWeapon.EtherBow,
    },
    levelRange: new NumberRange(7, 10),
    maxDurability: 11,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Accuracy]: 5, [AffixType.PercentDamage]: 5, [AffixType.LifeSteal]: 5, [AffixType.Evasion]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5 },
    },
    damage: new NumberRange(10, 22),
    damageClassificationsCount: 1,
    damageClassifications: [
      new ResourceChangeSource({ category: ResourceChangeSourceCategory.Magical, kineticDamageTypeOption: KineticDamageType.Piercing }),
    ],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.BodyArmor,
      baseItemType: BodyArmor.Rags,
    },
    levelRange: new NumberRange(1, 3),
    maxDurability: 12,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 3, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 3, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(1, 3),
    armorCategory: ArmorCategory.Cloth,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.BodyArmor,
      baseItemType: BodyArmor.Cloak,
    },
    levelRange: new NumberRange(2, 4),
    maxDurability: 14,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 3, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 3, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(2, 5),
    armorCategory: ArmorCategory.Cloth,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.BodyArmor,
      baseItemType: BodyArmor.Robe,
    },
    levelRange: new NumberRange(3, 7),
    maxDurability: 20,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 3, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 3, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(4, 8),
    armorCategory: ArmorCategory.Cloth,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.BodyArmor,
      baseItemType: BodyArmor.OfficersRobe,
    },
    levelRange: new NumberRange(6, 9),
    maxDurability: 22,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 3, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 3, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(8, 12),
    armorCategory: ArmorCategory.Cloth,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.BodyArmor,
      baseItemType: BodyArmor.MageRobe,
    },
    levelRange: new NumberRange(8, 10),
    maxDurability: 28,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 3, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 3, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(12, 20),
    armorCategory: ArmorCategory.Cloth,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.HeadGear,
      baseItemType: HeadGear.Cap,
    },
    levelRange: new NumberRange(1, 3),
    maxDurability: 12,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 3, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 3, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(1, 2),
    armorCategory: ArmorCategory.Cloth,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.HeadGear,
      baseItemType: HeadGear.Bandana,
    },
    levelRange: new NumberRange(2, 4),
    maxDurability: 14,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 3, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 3, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(2, 4),
    armorCategory: ArmorCategory.Cloth,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.HeadGear,
      baseItemType: HeadGear.PaddedCap,
    },
    levelRange: new NumberRange(3, 6),
    maxDurability: 14,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 3, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 3, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(3, 6),
    armorCategory: ArmorCategory.Cloth,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.HeadGear,
      baseItemType: HeadGear.Ribbon,
    },
    levelRange: new NumberRange(5, 10),
    maxDurability: 8,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 3, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 3, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(1, 1),
    armorCategory: ArmorCategory.Cloth,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.HeadGear,
      baseItemType: HeadGear.WizardHat,
    },
    levelRange: new NumberRange(7, 10),
    maxDurability: 20,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 3, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 3, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(6, 14),
    armorCategory: ArmorCategory.Cloth,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.BodyArmor,
      baseItemType: BodyArmor.LeatherVest,
    },
    levelRange: new NumberRange(3, 5),
    maxDurability: 16,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 3, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 3, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(2, 5),
    armorCategory: ArmorCategory.Leather,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.BodyArmor,
      baseItemType: BodyArmor.HardLeather,
    },
    levelRange: new NumberRange(5, 7),
    maxDurability: 18,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 3, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 3, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(4, 7),
    armorCategory: ArmorCategory.Leather,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.BodyArmor,
      baseItemType: BodyArmor.StuddedLeather,
    },
    levelRange: new NumberRange(6, 8),
    maxDurability: 24,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 3, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 3, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(7, 12),
    armorCategory: ArmorCategory.Leather,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.BodyArmor,
      baseItemType: BodyArmor.DemonsaurLeather,
    },
    levelRange: new NumberRange(8, 10),
    maxDurability: 36,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 3, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 3, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(14, 19),
    armorCategory: ArmorCategory.Leather,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.HeadGear,
      baseItemType: HeadGear.Eyepatch,
    },
    levelRange: new NumberRange(1, 3),
    maxDurability: 14,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 3, [AffixType.FlatArmorClass]: 5, [AffixType.Accuracy]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 3, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(2, 4),
    armorCategory: ArmorCategory.Leather,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.HeadGear,
      baseItemType: HeadGear.LeatherHat,
    },
    levelRange: new NumberRange(3, 5),
    maxDurability: 16,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 3, [AffixType.FlatArmorClass]: 5, [AffixType.Accuracy]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 3, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(3, 5),
    armorCategory: ArmorCategory.Leather,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.HeadGear,
      baseItemType: HeadGear.LeatherHelm,
    },
    levelRange: new NumberRange(4, 8),
    maxDurability: 18,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 3, [AffixType.FlatArmorClass]: 5, [AffixType.Accuracy]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 3, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(5, 8),
    armorCategory: ArmorCategory.Leather,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.HeadGear,
      baseItemType: HeadGear.DemonsaurHelm,
    },
    levelRange: new NumberRange(9, 10),
    maxDurability: 28,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 3, [AffixType.FlatArmorClass]: 5, [AffixType.Accuracy]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 3, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(10, 14),
    armorCategory: ArmorCategory.Leather,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.BodyArmor,
      baseItemType: BodyArmor.RingMail,
    },
    levelRange: new NumberRange(3, 5),
    maxDurability: 19,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(7, 10),
    armorCategory: ArmorCategory.Mail,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.BodyArmor,
      baseItemType: BodyArmor.ChainMail,
    },
    levelRange: new NumberRange(4, 6),
    maxDurability: 21,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(13, 16),
    armorCategory: ArmorCategory.Mail,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.BodyArmor,
      baseItemType: BodyArmor.SplintMail,
    },
    levelRange: new NumberRange(5, 7),
    maxDurability: 25,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(17, 20),
    armorCategory: ArmorCategory.Mail,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.BodyArmor,
      baseItemType: BodyArmor.FeatherMail,
    },
    levelRange: new NumberRange(6, 9),
    maxDurability: 29,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(21, 25),
    armorCategory: ArmorCategory.Mail,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.BodyArmor,
      baseItemType: BodyArmor.OhmushellMail,
    },
    levelRange: new NumberRange(8, 10),
    maxDurability: 52,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(20, 26),
    armorCategory: ArmorCategory.Mail,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.HeadGear,
      baseItemType: HeadGear.Hairpin,
    },
    levelRange: new NumberRange(3, 4),
    maxDurability: 12,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.LifeSteal]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(2, 2),
    armorCategory: ArmorCategory.Mail,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.HeadGear,
      baseItemType: HeadGear.Skullcap,
    },
    levelRange: new NumberRange(4, 5),
    maxDurability: 18,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.LifeSteal]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(8, 12),
    armorCategory: ArmorCategory.Mail,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.HeadGear,
      baseItemType: HeadGear.Coif,
    },
    levelRange: new NumberRange(5, 8),
    maxDurability: 19,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.LifeSteal]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(13, 15),
    armorCategory: ArmorCategory.Mail,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.HeadGear,
      baseItemType: HeadGear.OhmushellMask,
    },
    levelRange: new NumberRange(7, 10),
    maxDurability: 32,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.LifeSteal]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(15, 18),
    armorCategory: ArmorCategory.Mail,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.BodyArmor,
      baseItemType: BodyArmor.BreastPlate,
    },
    levelRange: new NumberRange(2, 4),
    maxDurability: 20,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 3, [AffixType.FlatArmorClass]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 3, [AffixType.Dexterity]: 3, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(10, 14),
    armorCategory: ArmorCategory.Plate,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.BodyArmor,
      baseItemType: BodyArmor.FieldPlate,
    },
    levelRange: new NumberRange(4, 6),
    maxDurability: 24,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 3, [AffixType.FlatArmorClass]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 3, [AffixType.Dexterity]: 3, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(16, 18),
    armorCategory: ArmorCategory.Plate,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.BodyArmor,
      baseItemType: BodyArmor.GothicPlate,
    },
    levelRange: new NumberRange(5, 8),
    maxDurability: 34,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 3, [AffixType.FlatArmorClass]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 3, [AffixType.Dexterity]: 3, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(20, 26),
    armorCategory: ArmorCategory.Plate,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.BodyArmor,
      baseItemType: BodyArmor.FullPlate,
    },
    levelRange: new NumberRange(8, 10),
    maxDurability: 42,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 3, [AffixType.FlatArmorClass]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 3, [AffixType.Dexterity]: 3, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(27, 30),
    armorCategory: ArmorCategory.Plate,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.HeadGear,
      baseItemType: HeadGear.Circlet,
    },
    levelRange: new NumberRange(2, 4),
    maxDurability: 18,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 3, [AffixType.FlatArmorClass]: 5, [AffixType.ArmorPenetration]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 3, [AffixType.Dexterity]: 3, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(3, 5),
    armorCategory: ArmorCategory.Plate,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.HeadGear,
      baseItemType: HeadGear.Crown,
    },
    levelRange: new NumberRange(4, 6),
    maxDurability: 16,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 3, [AffixType.FlatArmorClass]: 5, [AffixType.ArmorPenetration]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 3, [AffixType.Dexterity]: 3, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(10, 14),
    armorCategory: ArmorCategory.Plate,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.HeadGear,
      baseItemType: HeadGear.FullHelm,
    },
    levelRange: new NumberRange(6, 9),
    maxDurability: 31,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 3, [AffixType.FlatArmorClass]: 5, [AffixType.ArmorPenetration]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 3, [AffixType.Dexterity]: 3, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(15, 17),
    armorCategory: ArmorCategory.Plate,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.HeadGear,
      baseItemType: HeadGear.GreatHelm,
    },
    levelRange: new NumberRange(9, 10),
    maxDurability: 50,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 3, [AffixType.FlatArmorClass]: 5, [AffixType.ArmorPenetration]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 3, [AffixType.Dexterity]: 3, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(18, 22),
    armorCategory: ArmorCategory.Plate,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.Shield,
      baseItemType: Shield.PotLid,
    },
    levelRange: new NumberRange(0, 0),
    maxDurability: 8,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(2, 2),
    armorCategory: null,
    shieldSize: ShieldSize.Small,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.Shield,
      baseItemType: Shield.CabinetDoor,
    },
    levelRange: new NumberRange(1, 3),
    maxDurability: 16,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(3, 5),
    armorCategory: null,
    shieldSize: ShieldSize.Small,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.Shield,
      baseItemType: Shield.Heater,
    },
    levelRange: new NumberRange(2, 4),
    maxDurability: 22,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(10, 14),
    armorCategory: null,
    shieldSize: ShieldSize.Medium,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.Shield,
      baseItemType: Shield.Buckler,
    },
    levelRange: new NumberRange(3, 5),
    maxDurability: 18,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(9, 13),
    armorCategory: null,
    shieldSize: ShieldSize.Small,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.Shield,
      baseItemType: Shield.Pavise,
    },
    levelRange: new NumberRange(4, 6),
    maxDurability: 20,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(16, 19),
    armorCategory: null,
    shieldSize: ShieldSize.Large,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.Shield,
      baseItemType: Shield.Aspis,
    },
    levelRange: new NumberRange(5, 7),
    maxDurability: 18,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(15, 18),
    armorCategory: null,
    shieldSize: ShieldSize.Medium,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.Shield,
      baseItemType: Shield.LanternShield,
    },
    levelRange: new NumberRange(5, 6),
    maxDurability: 15,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.FlatDamage]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(13, 15),
    armorCategory: null,
    shieldSize: ShieldSize.Small,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.Shield,
      baseItemType: Shield.KiteShield,
    },
    levelRange: new NumberRange(6, 8),
    maxDurability: 24,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(19, 23),
    armorCategory: null,
    shieldSize: ShieldSize.Medium,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.Shield,
      baseItemType: Shield.TowerShield,
    },
    levelRange: new NumberRange(7, 10),
    maxDurability: 25,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(21, 28),
    armorCategory: null,
    shieldSize: ShieldSize.Large,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.Shield,
      baseItemType: Shield.AncientBuckler,
    },
    levelRange: new NumberRange(8, 10),
    maxDurability: 28,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(21, 24),
    armorCategory: null,
    shieldSize: ShieldSize.Small,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.Shield,
      baseItemType: Shield.GothicShield,
    },
    levelRange: new NumberRange(8, 10),
    maxDurability: 28,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.FlatArmorClass]: 5, [AffixType.Evasion]: 5, [AffixType.Agility]: 3 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.Durability]: 5, [AffixType.PercentArmorClass]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: new NumberRange(25, 28),
    armorCategory: null,
    shieldSize: ShieldSize.Medium,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.Ring,
      baseItemType: Ring.Ring,
    },
    levelRange: new NumberRange(3, 10),
    maxDurability: null,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.Accuracy]: 5, [AffixType.LifeSteal]: 5, [AffixType.Evasion]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.FlatDamage]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
  {
    baseItem: {
      equipmentType: EquipmentType.Amulet,
      baseItemType: Amulet.Amulet,
    },
    levelRange: new NumberRange(3, 10),
    maxDurability: null,
    requirements: {},
    possibleAffixes: {
      prefix: { [AffixType.Mp]: 5, [AffixType.Accuracy]: 5, [AffixType.LifeSteal]: 5, [AffixType.Evasion]: 5, [AffixType.ArmorPenetration]: 5, [AffixType.Agility]: 5 },
      suffix: { [AffixType.Strength]: 5, [AffixType.Spirit]: 5, [AffixType.Dexterity]: 5, [AffixType.Vitality]: 5, [AffixType.Hp]: 5, [AffixType.FlatDamage]: 5 },
    },
    damage: null,
    damageClassificationsCount: null,
    damageClassifications: [],
    armorClass: null,
    armorCategory: null,
    shieldSize: null,
  },
];
